### ISSUE TITLE
Any way to split pools for cards?

### ISSUE THREAD

**Issue by romajc84** [Sniffdog/Hashsynminer#1]
Was messing around with Hashsynminer.

I have 6 1080 ti's so I really have no need for it as of yet.

But I was wondering, is there any way to have 2 cards on zpool, 2 on ahash, 2 on hashrefinery?

This way we could test which pool is the most profitable more reliably than relying on the estimated profit per day.

**Comment by Sniffdog** [comment]
Interesting... I will have a look at it in the next couple of days

**Comment by Sniffdog** [comment]
We will just have to make three Hashsynminer_start.bats for each pool instance for now...

I'll add the files today in a folder in the Mastercopy

EDIT: Added into a folder... you will have to copy/paste to Hashsynminer-master... then add your info to each .bat

**Comment by romajc84** [comment]
So I need to input the cards and algos I want in each pool file?

Would card 1 and 2 look like this; -SplitSniffCC0 '0 1' -SplitSniffEWBF1 '0,1'

Then run them separately?

**Comment by Sniffdog** [comment]
no you would have -SplitSniffCC0 '0' -SplitSniffEWBF0 '0' -SplitSniffCC1 '1' -SplitSniffEWBF1 '1'

to run each algo on seperate card
