### ISSUE TITLE
Too many instances

### ISSUE THREAD

**Issue by Nickduino** [Sniffdog/Hashsynminer#11]
Here's my *.bat:

`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username Tyredas -Workername Beeboop -RigName Hashsynminer001 -Currency EUR -Passwordcurrency BTC -Passwordcurrency1 BTC -interval 90 -Delay 1 -SplitSniffCC0 '0,1,2,3,4,5' -SplitSniffCC1 '6,7,8,9,10,11' -SplitSniffEWBF0 '0 1 2 3 4 5' -SplitSniffEWBF1 '6 7 8 9 10 11' -Wallet BTC1 -Wallet1 BTC2 -Location Europe -PoolName zpool,Hashrefinery,MPH,ahashpool,zergpool -Type nvidia,nvidia1 -Algorithm tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,xevan,blake2s,x17,lyra2z,timetravel,polytimos,phi,hsr -Donate 5`

I want to split my rig into two, simple.

It works with the first half: I have a CCminer window opening 6 threads. It doesn't with the second half: there are 6 more instances of CCminer, each with **one** thread.

![Screenshot](https://image.ibb.co/n7B43S/screenshot.png)

Any idea about what's wrong?
(I'm opening another issue for the connection error)

**Comment by Sniffdog** [comment]
yeah we are going to add excavator and enemy raven this weekend so will be doing diagnostics with hashsynminer

nope your batch looks right.. not to sure why hashsynminer is opening so many ccminers on you

We will go through Hashsynminer...


Looks like your missing -StatsInterval in bat file...

**Comment by Nickduino** [comment]
I added it, it does the same

**Comment by Sniffdog** [comment]
ok then please use -Location US while benching because polytimos is on zpool and zpool is not in europe


or if you know exactly how many algos there is being used in Europe... then remove the ones not listed 

I always try to mention to bench everything before changing the start batch file (except for your info of course)

**Comment by Nickduino** [comment]
Still doesn't work

I have four ccminer instances running 1 thread with this batch:
`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -StatsInterval 1 -Username [Username] -Workername Hashsynminer1 -RigName Hashsynminer001 -Currency EUR -Passwordcurrency BTC -interval 90 -Delay 1 -SplitSniffCC0 '0,1,2,3' -SplitSniffEWBF0 '0 1 2 3' -Wallet [MyWallet] -Location US -PoolName zpool,Hashrefinery,MPH,ahashpool,zergpool,blazepool -Type nvidia,nvidia1,nvidia2,nvidia3 -Algorithm tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,xevan,blake2s,x17,lyra2z,timetravel,polytimos,phi,hsr,x16r,hmq1725 -Donate 5`


(I'm running only 4 cards: my end goal is to have three groups of 4 cards on 3 different pools)
