### ISSUE TITLE
Sniffdog miner's  update on Hashsynminer

### ISSUE THREAD

**Issue by kingyem** [Sniffdog/Hashsynminer#14]
Hello, 

I am very excited to see sniffdog miner's updates on Hashsynminer please.

Thank you.

**Comment by Nickduino** [comment]
Last commits were 3 weeks ago, I don't think you can call that a dead repo.

**Comment by kingyem** [comment]
True, should have worded it better. 

I'm excited to see Hashsynminer with updates from the original sniffdog miner hence this thread.
