### ISSUE TITLE
EWBF miner mines with all GPU instead of the designated GPU 

### ISSUE THREAD

**Issue by kingyem** [Sniffdog/Hashsynminer#2]
Hello.

Reporting, i made 2 batch files for 
1)-Type nvidia ; and 
2)-Type nvidia1. 

While benchmarking each, the EWBF miner would run both GPU0 and GPU1 together for each batch file instead of the designated GPU separately. The only command that i changed was for the -Type command and wallet address.

For other miners, all is working as intended.

**Comment by Sniffdog** [comment]
I'll look at it as soon as I wake up and have a coffee . Thanks...

Which bat files where you using and can you give some more info please.... show what you used... GPU0 could mean $SplitsniffEWBF0 or  $SplitSniffCC0

**Comment by kingyem** [comment]
sorry didnt notice the update

was using the 
Hashynminer_start.bat file, then edited so that both will run zpool only. 

1) powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username * -Workername * -RigName Hashsynminer001 -Currency USD -Passwordcurrency BTC -Passwordcurrency1 BTC -Passwordcurrency2 BTC -Passwordcurrency3 BTC -Passwordcurrency4 BTC -Passwordcurrency5 BTC -Passwordcurrency6 BTC -Passwordcurrency7 BTC -interval 300 -Delay 1 -SplitSniffCC0 '0' -SplitSniffCC1 '1' -SplitSniffCC2 '2' -SplitSniffCC3 '3' -SplitSniffCC4 '4' -SplitSniffCC5 '5' -SplitSniffCC6 '6' -SplitSniffCC7 '7' -SplitSniffEWBF0 '0' -SplitSniffEWBF1 '1' -SplitSniffEWBF2 '2' -SplitSniffEWBF3 '3' -SplitSniffEWBF4 '4' -SplitSniffEWBF5 '5' -SplitSniffEWBF6 '6' -SplitSniffEWBF7 '7' -Wallet * -Wallet1 * -Wallet2 * -Wallet3 * -Wallet4 * -Wallet5 * -Wallet6 * -Wallet7 * -Location US -PoolName zpool -Type nvidia -Algorithm tribus,c11,lbry,skein,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,x17,timetravel,polytimos,phi,hsr -Donate 5

2) powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username * -Workername * -RigName Hashsynminer001 -Currency USD -Passwordcurrency BTC -Passwordcurrency1 BTC -Passwordcurrency2 BTC -Passwordcurrency3 BTC -Passwordcurrency4 BTC -Passwordcurrency5 BTC -Passwordcurrency6 BTC -Passwordcurrency7 BTC -interval 300 -Delay 1 -SplitSniffCC0 '0' -SplitSniffCC1 '1' -SplitSniffCC2 '2' -SplitSniffCC3 '3' -SplitSniffCC4 '4' -SplitSniffCC5 '5' -SplitSniffCC6 '6' -SplitSniffCC7 '7' -SplitSniffEWBF0 '0' -SplitSniffEWBF1 '1' -SplitSniffEWBF2 '2' -SplitSniffEWBF3 '3' -SplitSniffEWBF4 '4' -SplitSniffEWBF5 '5' -SplitSniffEWBF6 '6' -SplitSniffEWBF7 '7' -Wallet * -Wallet1 * -Wallet2 * -Wallet3 * -Wallet4 * -Wallet5 * -Wallet6 * -Wallet7 * -Location US -PoolName zpool -Type nvidia1 -Algorithm tribus,c11,lbry,skein,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,x17,timetravel,polytimos,phi,hsr -Donate 5

other than running them separately on zpool, i only changed my details, -Type and -Algorithm

**Comment by Sniffdog** [comment]
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username * -Workername * -RigName Hashsynminer001 -Currency USD -Passwordcurrency BTC -interval 300 -Delay 1 -SplitSniffCC0 '0' -SplitSniffEWBF0 '0' -Wallet *-Location US -PoolName zpool -Type nvidia -Algorithm tribus,c11,lbry,skein,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,x17,timetravel,polytimos,phi,hsr -Donate 5

    powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username * -Workername * -RigName Hashsynminer002 -Currency USD -Passwordcurrency1 BTC -interval 300 -Delay 1 -SplitSniffCC0 '1' -SplitSniffEWBF0 '1' -Wallet1 * -Location US -PoolName zpool -Type nvidia1 -Algorithm tribus,c11,lbry,skein,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,x17,timetravel,polytimos,phi,hsr -Donate 5

Think of it as slots in your rig....

**Comment by kingyem** [comment]
![equihash](https://user-images.githubusercontent.com/35198970/34918251-a49d925e-f98a-11e7-8589-1b930bf31c37.png)

with this command line:

> powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username * -Workername * -RigName Hashsynminer001 -Currency USD -Passwordcurrency BTC -interval 300 -Delay 1 -SplitSniffCC0 '0' -SplitSniffEWBF0 '0' -Wallet *-Location US -PoolName zpool -Type nvidia -Algorithm equihash,tribus,c11,lbry,skein,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,x17,timetravel,polytimos,phi,hsr -Donate 5

After using the command line, it still is using both cards

**Comment by Sniffdog** [comment]
to bad i can't see by the screen how ewbf is running....

**Comment by kingyem** [comment]
From the picture, when EWBF0 is running, both devices ( CUDA : Device : 0 and CUDA : Device 1) are runnning

**Comment by kingyem** [comment]
a new issue cropped up,
when executing the batch file for nvidia1 with command line 

> powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username * -Workername * -RigName Hashsynminer002 -Currency USD -Passwordcurrency1 BTC -interval 300 -Delay 1 -SplitSniffCC0 '1' -SplitSniffEWBF0 '1' -Wallet1 * -Location US -PoolName zpool -Type nvidia1 -Algorithm tribus,c11,lbry,skein,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,x17,timetravel,polytimos,phi,hsr -Donate 5

 No pools were detected

**Comment by Sniffdog** [comment]
"equihash" = ' -d $SplitsniffEWBF0' #Equihash change to "equihash" = " -d $SplitsniffEWBF0" #Equihash

the quotations are different surrounding the command...
Repaired in master files...

If your only using one pool expect the API not to detect the pool... why we try to create backup pools and if your monitoring.... well you can include that in price for downtime at that pool

**Comment by kingyem** [comment]
I edited the miner file but both GPUs are still running

**Comment by Sniffdog** [comment]
Alright... I will re-download and check out using your own .bat file

....once Zpool API works (sigh)

**Comment by kingyem** [comment]
kudos 👍 

this is my first time using github so if i am stepping out of line or being a nuisance with all these issues, do let me know 👍

**Comment by Sniffdog** [comment]
nah not really.. if there is an issue with hashsynminer... we need to know...

**Comment by Sniffdog** [comment]
we just built another 8 card 1080ti rig in the UK so I'm close to the computer...

**Comment by kingyem** [comment]
here in Malaysia the price hike just started a few days ago, the difference is significant

am really excited to be part of this miner's progress 👍

**Comment by Sniffdog** [comment]
"equihash" = ' -d $SplitsniffEWBF0' #Equihash change to "equihash" = " -d $SplitSniffEWBF0" #Equihash

...just checking if we need a Capital S in SplitSniffEWBF0

-works on '0'

**Comment by Sniffdog** [comment]
Zpool....

We're doing some server maintenance on all servers. Will require a reboot of them all. Will stagger them to minimize impact but expect some bumps on stratums and disappearing coin inventory.

...so I'm gonna open up mph as well to check equihash

**Comment by Sniffdog** [comment]
for card 0 in Miners Folder "equihash" = " --cuda_devices $SplitSniffEWBF0" #Equihash
for card 1 in Miners Folder "equihash" = " --cuda_devices $SplitSniffEWBF1" #Equihash

Rest have all been repaired in master copy.. thank you so much for spotting this!

I'll put out a new release and compliment you for spotting this :)

**Comment by kingyem** [comment]
i'm just glad i could help 👍 

plus you did all the leg work, kudos! :)

**Comment by kingyem** [comment]
alright its working as intended now :D 

congratulations and thank you :)
