### ISSUE TITLE
remove benchmark results

### ISSUE THREAD

**Issue by jbates58** [Sniffdog/Hashsynminer#3]
hi all.

i had an issue where during benchmarking, something must have glitched. i have 4 1080TI's in my rig. and its showing 3 are getting around the $17/day mark for a specific coin, and on the 4th its showing nearly $500/day. hahaha. not sure what the go is, but i just want to remove the benchmark file, or even adjust it to the same as the others to ensure more accurate switching. but i cant find the file. 

Jason

**Comment by Sniffdog** [comment]
stats folder... just try to re-bench number "4" card by deleting that miner and algo in the list

**Comment by Sniffdog** [comment]
did some minor repairs.. found a few bugs in miner's folder... made a new release
