### ISSUE TITLE
x11evo not benchmarking on separate batch file

### ISSUE THREAD

**Issue by kingyem** [Sniffdog/Hashsynminer#4]
Hello,

![1 2](https://user-images.githubusercontent.com/35198970/34916902-06891846-f97a-11e7-9b67-37bc22ff1d58.png)

the command line i used is the same as in [https://github.com/Sniffdog/Hashsynminer/issues/2](url), didn't notice it yesterday but the 2nd window doesn't show x11evo in the list.

**Comment by Sniffdog** [comment]
Thanks... it wasn't opened in CcminerTpruvot1.ps1

Repaired it in master copy but if you want to...edit CcminerTpruvot1.ps1 in Miners Folder and remove the # in front of x11evo

**Comment by Sniffdog** [comment]
1) powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username * -Workername * -RigName Hashsynminer001 -Currency USD -Passwordcurrency BTC -interval 300 -Delay 1 -SplitSniffCC0 '0' -SplitSniffEWBF0 '0'  -Wallet *-Location US -PoolName zpool -Type nvidia -Algorithm tribus,c11,lbry,skein,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,x17,timetravel,polytimos,phi,hsr -Donate 5

2) powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username * -Workername * -RigName Hashsynminer002 -Currency USD -Passwordcurrency1 BTC -interval 300 -Delay 1 -SplitSniffCC0 '1' -SplitSniffEWBF0 '1' -Wallet1 * -Location US -PoolName zpool -Type nvidia1 -Algorithm tribus,c11,lbry,skein,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,x17,timetravel,polytimos,phi,hsr -Donate 5

1 card 0 slot
2 card 1 slot
etc
