### ISSUE TITLE
Scrypt Algorithm causes Failed miner

### ISSUE THREAD

**Issue by kingyem** [Sniffdog/Hashsynminer#5]
Hello,

Just downloaded 0.4, and using the scrypt algo in ahashpool causes the miner to fail.

**Comment by Sniffdog** [comment]
yeah i didn't realize i had that opened and never tested it since scrypt miners are kicking GPU butts...

but I will change from scrypt alexis to scrypt Tpruvot... thank you :)

**Comment by Sniffdog** [comment]
I also had someone say to set intensity to -i 10 in tpruvot scrypt if your having troubles with it

**Comment by kingyem** [comment]
tried both and benchmark runs, but after benchmark is finished, scrypt was removed from the algo list

**Comment by Sniffdog** [comment]
Sorry for the late reply... been at the new pool zergpool fixing issues... yeah this is why I left them closed due to scrypt (asic) mining now...
