### ISSUE TITLE
Benchmarking multiple pools?

### ISSUE THREAD

**Issue by Nickduino** [Sniffdog/Hashsynminer#8]
I don't like how Githubs call things "issues" when they are just questions but, here we go...

I'm not sure I got it right (and I haven't received my power supplies yet to test it)...do you have to choose **one** pool and Hashsynminer will benchmark each algo or is Hashsynminer able to benchmark the various pools and mine at whatever pool is most profitable (with the most profitable algo)?

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username Tyredas -Workername Beeboop -RigName Hashsynminer001 -Currency EUR -Passwordcurrency BTC -Passwordcurrency1 BTC -interval 90 -Delay 1 -SplitSniffCC0 '0,1,2,3,4,5' -SplitSniffCC1 '6,7,8,9,10,11' -SplitSniffEWBF0 '0 1 2 3 4 5' -SplitSniffEWBF1 '6 7 8 9 10 11' -Wallet _BTC1_ -Wallet1 _BTC2_ -Location Europe -PoolName zpool,Hashrefinery,MPH,ahashpool,zergpool -Type nvidia,nvidia1,nvidia2,nvidia3,nvidia4,nvidia5,nvidia6,nvidia7,nvidia8,nvidia9,nvidia10,nvidia11 -Algorithm tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,xevan,blake2s,x17,lyra2z,timetravel,polytimos,phi,hsr -Donate 5

**Comment by Sniffdog** [comment]
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username Tyredas -Workername Beeboop -RigName Hashsynminer001 -Currency EUR -Passwordcurrency BTC -Passwordcurrency1 BTC -interval 90 -Delay 1 -SplitSniffCC0 '0,1,2,3,4,5' -SplitSniffCC1 '6,7,8,9,10,11' -SplitSniffEWBF0 '0 1 2 3 4 5' -SplitSniffEWBF1 '6 7 8 9 10 11' -Wallet BTC1 -Wallet1 BTC2 -Location Europe -PoolName zpool,Hashrefinery,MPH,ahashpool,zergpool -Type nvidia,nvidia1 -Algorithm tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,xevan,blake2s,x17,lyra2z,timetravel,polytimos,phi,hsr -Donate 5

This setup.... will mine one address with half your rig and mine another address with the other half of your rig

If you want to mine different algos with the other half of your rig.... make a folder and download 2 copies of hashsynminer and run one at zero and the other at 1....

HashsynminerA in folder:

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username Tyredas -Workername Beeboop -RigName Hashsynminer001 -Currency EUR -Passwordcurrency BTC -interval 90 -Delay 1 -SplitSniffCC0 '0,1,2,3,4,5' -SplitSniffEWBF0 '0 1 2 3 4 5' -SplitSniffEWBF1 -Wallet BTC -Location Europe -PoolName zpool,Hashrefinery,MPH,ahashpool,zergpool -Type nvidia, -Algorithm tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,xevan,blake2s,x17,lyra2z,timetravel,polytimos,phi,hsr -Donate 5

HashsynminerB in folder:

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\Hashsynminer.ps1 -Username Tyredas -Workername Beeboop -RigName Hashsynminer001 -Currency EUR -Passwordcurrency1 BTC -interval 90 -Delay 1 -SplitSniffCC1 '6,7,8,9,10,11' -SplitSniffEWBF1 '6 7 8 9 10 11' -Wallet BTC1 -Wallet1 BTC2 -Location Europe -PoolName zpool,Hashrefinery,MPH,ahashpool,zergpool -Type nvidia1, -Algorithm tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,xevan,blake2s,x17,lyra2z,timetravel,polytimos,phi,hsr -Donate 5

 HashsynminerB.....Yes, you have to keep the _Wallet command like that in just keep it the same address in both and you can change algos to what you want

**Comment by Nickduino** [comment]
> This setup.... will mine one address with half your rig and mine another address with the other half of your rig

Great, that's what I want!


My other question wasn't clear: do you **1.** let SplitSniff choose whatever pool is most profitable **or** do you **2.** choose a pool and SplitSniff only choose the most profitable?
Seeing your answer to my first question, I believe it's **1.**....which begs the following comment: some pool only pay in BTC, while others accept to exchange in other currencies. I'd like to be paid in ETH whenever possible and the current config file only allows one currency for all pools. Would it be possible specify 2 wallet addresses and 1 currency **for each pool**?

**Comment by Sniffdog** [comment]
Haha! well you can try two different wallets addresses and see what happens.... hard to find pools that pay in Ethereum... I know I have a limited amount of pools that accept Litecoin (miningpoolhub,zpool,zergpool)

The reason to have other pools is for backup.... once you get familiar with hashsynminer you will see the potential Hashsynminer offers... and you can really fine tune every aspect...

**Comment by Nickduino** [comment]
Alright, so it doesn't arbitrate between pools but uses the first one in the list and only goes to the second (and third, and...) if it cannot connect to the first one?

What if a pool is online but one algorithm (the most profitable) not available?

**Comment by Sniffdog** [comment]
yes it does arbitrate between which is the better algo to mine at that single instant when Hashsynminer checks the API
